// Language test suite - covers LANGUAGE.md section by section.
// Run: node Test/LanguageTests.js [filter] [--verbose] [--memcheck] [--leaks] [--bugs]

const { runSuite } = require("./harness");

const lines = (...xs) => xs.join("\n");

// wraps statements in a main() that returns 0
const main = body => `main() {\n${body}\n    return 0;\n}\n`;

const tests = [

    // ── Program structure ────────────────────────────────────────────────

    { name: "structure: minimal main", source: main(`print(1);`), expected: "1" },
    { name: "structure: main written as 'function main()'",
      source: `function main() {\n    print(7);\n    return 0;\n}`, expected: "7" },
    { name: "structure: function declared after use",
      source: main(`print(later(4));`) + `function later(int x) { return x * 10; }`, expected: "40" },
    { name: "structure: main returning non-zero sets exit code",
      source: `main() {\n    print(1);\n    return 3;\n}`, expected: "1", exitCode: 3 },
    { name: "structure: line comments everywhere",
      source: `// leading comment\nmain() { // after brace\n    print(1); // trailing\n    // own line\n    return 0;\n}\n// final comment without newline at end`,
      expected: "1" },

    // ── Types and variables ──────────────────────────────────────────────

    { name: "vars: var/let/const are all accepted",
      source: main(`var a = 1;\n let b = 2;\n const c = 3;\n print(a + b + c);`), expected: "6" },
    { name: "vars: const is not enforced (documented)",
      source: main(`const c = 3;\n c = 4;\n print(c);`), expected: "4" },
    { name: "vars: inferred string",
      source: main(`var s = "hi";\n print(s);`), expected: "hi" },
    { name: "vars: inferred float",
      source: main(`var f = 1.5;\n print(f);`), expected: "1.5" },
    { name: "vars: bool prints as 1/0",
      source: main(`var bool t = true;\n var bool f = false;\n print(t);\n print(f);`), expected: "1\n0" },
    { name: "vars: int to float widening on declaration",
      source: main(`var float f = 3;\n print(f * 1.5);`), expected: "4.5" },
    { name: "vars: float to int truncation on declaration",
      source: main(`var int n = 9.9;\n print(n);`), expected: "9" },
    { name: "vars: negative float to int truncates towards zero",
      source: main(`var int n = -9.9;\n print(n);`), expected: "-9" },
    { name: "vars: reassignment",
      source: main(`var x = 1;\n x = 2;\n x = x + 5;\n print(x);`), expected: "7" },
    { name: "vars: block scoped variable with same name in sibling blocks",
      source: main(`if (true) { var a = 1; print(a); }\n if (true) { var a = 2; print(a); }`), expected: "1\n2" },
    { name: "vars: hex literals",
      source: main(`print(0xFF);\n print(0x10);\n print(0x0);\n print(0XaB);`), expected: "255\n16\n0\n171" },

    // 64-bit integers
    { name: "int64: print value above 2^31",
      source: main(`var int a = 2147483647;\n a = a + 1;\n print(a);`), expected: "2147483648" },
    { name: "int64: print value below -2^31",
      source: main(`var int a = -2147483647;\n a = a - 10;\n print(a);`), expected: "-2147483657" },
    { name: "int64: multiplication into 64-bit range",
      source: main(`var int a = 100000;\n var int b = a * a;\n print(b / 1000);`), expected: "10000000" },
    { name: "int64: large product printed",
      source: main(`var int a = 3000000;\n print(a * a);`), expected: "9000000000000" },
    { name: "int64: literal above 2^31",
      source: main(`var int big = 3000000000;\n print(big / 1000);`), expected: "3000000" },
    { name: "int64: negative literal below -2^31",
      source: main(`var int big = -3000000000;\n print(big / 1000);`), expected: "-3000000" },
    { name: "int64: hex literal above 2^31",
      source: main(`var int m = 0xFFFFFFFF;\n print(m / 65536);`), expected: "65535" },
    { name: "int64: literal above 2^31 in comparison",
      source: main(`var int a = 800000000;\n if (a < 5000000000) { print(1); } else { print(0); }`), expected: "1" },
    { name: "int64: overflow wraps",
      source: main(`var int a = 4611686018427387904;\n var int b = a + a;\n if (b < 0) { print(1); } else { print(0); }`),
      expected: "1" },
    { name: "int64: factorial 20",
      source: `function fact(int n) {\n    if (n <= 1) { return 1; }\n    return n * fact(n - 1);\n}\n` +
              main(`print(fact(20));`), expected: "2432902008176640000" },
    { name: "int64: factorial 20 checked without printing",
      source: `function fact(int n) {\n    if (n <= 1) { return 1; }\n    return n * fact(n - 1);\n}\n` +
              main(`print(fact(20) / 1000000 / 1000000);`), expected: "2432902" },

    { name: "int64: decimal literal above 2^53 keeps every digit",
      source: main(`var int a = 9007199254740993;\n print(a);`), expected: "9007199254740993" },
    { name: "int64: largest int literal",
      source: main(`var int a = 9223372036854775807;\n print(a);\n print(a % 10);`), expected: "9223372036854775807\n7" },
    { name: "int64: 64-bit hex literal",
      source: main(`var int a = 0x7FFFFFFFFFFFFFFF;\n print(a);\n var int m = 0xFFFFFFFFFFFFFFFF;\n print(m);`), expected: "9223372036854775807\n-1" },

    // ── Operators ────────────────────────────────────────────────────────

    { name: "ops: precedence * over +",
      source: main(`var a = 2;\n print(a + 3 * 4);`), expected: "14" },
    { name: "ops: parentheses",
      source: main(`var a = 2;\n print((a + 3) * 4);`), expected: "20" },
    { name: "ops: subtraction is left associative",
      source: main(`var a = 10;\n print(a - 3 - 2);`), expected: "5" },
    { name: "ops: division is left associative",
      source: main(`var a = 100;\n print(a / 10 / 5);`), expected: "2" },
    { name: "ops: mixed * / % same precedence left to right",
      source: main(`var a = 7;\n print(a * 3 % 4);\n print(a % 4 * 3);`), expected: "1\n9" },
    { name: "ops: comparison binds looser than arithmetic",
      source: main(`var a = 2;\n print(a + 1 == 3);`), expected: "1" },
    { name: "ops: && binds tighter than ||",
      source: main(`var t = 1;\n var f = 0;\n print(t || f && f);`), expected: "1"  },
    { name: "ops: integer division truncates towards zero",
      source: main(`var a = 7;\n var b = -7;\n print(a / 2);\n print(b / 2);`), expected: "3\n-3" },
    { name: "ops: modulo takes the sign of the dividend",
      source: main(`var a = 7;\n var b = -7;\n print(a % 3);\n print(b % 3);`), expected: "1\n-1" },
    { name: "ops: all comparisons on ints",
      source: main(`var a = 3;\n var b = 5;\n print(a < b);\n print(a <= b);\n print(a > b);\n print(a >= b);\n print(a == b);\n print(a != b);\n print(a <= 3);\n print(a >= 3);`),
      expected: "1\n1\n0\n0\n0\n1\n1\n1" },
    { name: "ops: unary minus on variable and expression",
      source: main(`var a = 4;\n print(-a);\n print(-(a + 1));`), expected: "-4\n-5" },
    { name: "ops: logical not",
      source: main(`var a = 0;\n var b = 5;\n print(!a);\n print(!b);\n print(!!b);`), expected: "1\n0\n1" },
    { name: "ops: && and || produce 0 or 1",
      source: main(`var a = 3;\n var b = 7;\n var z = 0;\n print(a && b);\n print(z || b);\n print(a || z);\n print(z && b);`),
      expected: "1\n1\n1\n0"  },
    { name: "ops: && short-circuits",
      source: `function side() {\n    print(99);\n    return 1;\n}\n` + main(`var z = 0;\n if (z && side()) { print(1); }\n print(2);`),
      expected: "2" },
    { name: "ops: || short-circuits",
      source: `function side() {\n    print(99);\n    return 1;\n}\n` + main(`var o = 1;\n if (o || side()) { print(1); }`),
      expected: "1" },
    { name: "ops: && and || in a loop condition",
      source: main(`var i = 0;\n var n = 0;\n while (i < 100 && (n < 30 || i % 2 == 0)) {\n n += 3;\n i++;\n }\n print(i);\n print(n);`),
      expected: "11\n33", memcheck: true },
    { name: "ops: deeply nested && and ||",
      source: `function f(int a, int b, int c, int d) { return a && (b || (c && !d)); }\n` +
              main(`print(f(1, 0, 1, 0));\n print(f(1, 0, 1, 1));\n print(f(0, 1, 1, 0));\n print(f(1, 1, 0, 1));`),
      expected: "1\n0\n0\n1", memcheck: true },
    { name: "ops: nested short-circuit skips side effects at every level",
      source: `function side(int v) {\n    print(v);\n    return v;\n}\n` +
              main(`var r = side(0) && (side(1) || side(2));\n print(r);\n var q = side(3) || (side(0) && side(4));\n print(q);`),
      expected: "0\n0\n3\n1", memcheck: true },
    { name: "ops: compound assignment operators",
      source: main(`var x = 10;\n x += 5;\n print(x);\n x -= 3;\n print(x);\n x *= 2;\n print(x);\n x /= 4;\n print(x);\n x %= 4;\n print(x);`),
      expected: "15\n12\n24\n6\n2" },
    { name: "ops: compound assignment with expression on the right",
      source: main(`var x = 1;\n var y = 2;\n x += y * 3 + 1;\n print(x);`), expected: "8" },
    { name: "ops: postfix increment returns old value",
      source: main(`var a = 5;\n var b = a++;\n print(b);\n print(a);`), expected: "5\n6"  },
    { name: "ops: postfix decrement returns old value",
      source: main(`var a = 5;\n var b = a--;\n print(b);\n print(a);`), expected: "5\n4"  },
    { name: "ops: prefix increment returns new value",
      source: main(`var a = 5;\n var b = ++a;\n print(b);\n print(a);`), expected: "6\n6" },
    { name: "ops: prefix decrement as a statement",
      source: main(`var a = 5;\n --a;\n print(a);`), expected: "4" },

    // constant folding
    { name: "fold: integer arithmetic",
      source: main(`print(2 + 3 * 4);\n print(20 - 5 - 5);\n print(-(3 + 4));`), expected: "14\n10\n-7" },
    { name: "fold: integer division truncates",
      source: main(`print(7 / 2);`), expected: "3" },
    { name: "fold: negative integer division truncates towards zero",
      source: main(`print(-7 / 2);`), expected: "-3" },
    { name: "fold: integer division used in a variable",
      source: main(`var int half = 9 / 2;\n print(half * 2);`), expected: "8" },
    { name: "fold: comparisons",
      source: main(`print(3 < 5);\n print(3 > 5);\n print(4 == 4);\n print(4 != 4);`), expected: "1\n0\n1\n0" },
    { name: "fold: float product keeps float type",
      source: main(`var x = 2.0 * 3.0;\n print(x / 4.0);`), expected: "1.5" },
    { name: "fold: fractional float result",
      source: main(`var float q = 1.0 / 4.0;\n print(q);`), expected: "0.25" },
    { name: "fold: float product with integral result above 2^32",
      source: main(`var b = 396.0 * 396.0 * 396.0 * 396.0;\n print(b / 2.0);`), expected: "1.22956e+10" },
    { name: "fold: integer product above 2^31",
      source: main(`var int big = 100000 * 100000;\n print(big / 1000);`), expected: "10000000" },

    { name: "fold: integer overflow wraps at 64 bits",
      source: main(`print(9223372036854775807 + 1);`), expected: "-9223372036854775808" },
    { name: "fold: float literal times int literal is a float",
      source: main(`var x = 2.5 * 2;\n print(x / 2.0);`), expected: "2.5" },
    { name: "fold: folded float passed to a float parameter",
      source: `import math;\n` + main(`print(math_sqrt(2.0 * 8.0));`), expected: "4" },

    // ── Control flow ─────────────────────────────────────────────────────

    { name: "if: no else, condition false",
      source: main(`var a = 0;\n if (a) { print(1); }\n print(2);`), expected: "2" },
    { name: "if: else-if chain picks each branch",
      source: `function pick(int x) {\n    if (x < 0) { return -1; } else if (x == 0) { return 0; } else if (x < 10) { return 1; } else { return 2; }\n}\n` +
              main(`print(pick(-5));\n print(pick(0));\n print(pick(5));\n print(pick(50));`),
      expected: "-1\n0\n1\n2" },
    { name: "if: nested ifs",
      source: main(`var a = 3;\n var b = 4;\n if (a > 1) {\n if (b > 5) { print(1); } else { print(2); }\n } else { print(3); }`),
      expected: "2" },
    { name: "if: condition is any non-zero int",
      source: main(`var a = -3;\n if (a) { print(1); } else { print(0); }`), expected: "1" },
    { name: "if: literal true/false branches are removed by DCE",
      source: main(`if (true) { print(1); } else { print(2); }\n if (false) { print(3); } else { print(4); }\n if (false) { print(5); }`),
      expected: "1\n4"  },

    { name: "while: counts",
      source: main(`var i = 0;\n while (i < 5) { i++; }\n print(i);`), expected: "5" },
    { name: "while: break",
      source: main(`var i = 0;\n while (true) {\n if (i == 3) { break; }\n i++;\n }\n print(i);`), expected: "3" },
    { name: "while: continue",
      source: main(`var i = 0;\n var s = 0;\n while (i < 10) {\n i++;\n if (i % 2 == 0) { continue; }\n s += i;\n }\n print(s);`),
      expected: "25" },
    { name: "while: nested loops with inner break",
      source: main(`var i = 0;\n var n = 0;\n while (i < 4) {\n var j = 0;\n while (true) {\n if (j == i) { break; }\n n++;\n j++;\n }\n i++;\n }\n print(n);`),
      expected: "6" },

    { name: "for: basic sum",
      source: main(`var s = 0;\n for (var int i = 1; i <= 10; i++) { s += i; }\n print(s);`), expected: "55" },
    { name: "for: step of two",
      source: main(`var s = 0;\n for (var int i = 0; i < 10; i += 2) { s += i; }\n print(s);`), expected: "20" },
    { name: "for: counting down",
      source: main(`for (var int i = 3; i > 0; i--) { print(i); }`), expected: "3\n2\n1" },
    { name: "for: continue still runs the update",
      source: main(`var s = 0;\n for (var int i = 0; i < 10; i++) {\n if (i % 2 == 0) { continue; }\n s += i;\n }\n print(s);`),
      expected: "25" },
    { name: "for: break",
      source: main(`var last = 0;\n for (var int i = 0; i < 100; i++) {\n if (i == 7) { break; }\n last = i;\n }\n print(last);`),
      expected: "6" },
    { name: "for: init assigns an existing variable",
      source: main(`var i = 99;\n for (i = 0; i < 3; i++) { }\n print(i);`), expected: "3" },
    { name: "for: nested loops",
      source: main(`var n = 0;\n for (var int i = 0; i < 4; i++) {\n for (var int j = 0; j < 3; j++) { n += i * j; }\n }\n print(n);`),
      expected: "18" },
    { name: "for: loop that never runs",
      source: main(`for (var int i = 5; i < 5; i++) { print(i); }\n print(0);`), expected: "0" },

    { name: "for-in: sum",
      source: main(`var int[] a = [1, 2, 3, 4];\n var s = 0;\n for (v in a) { s += v; }\n print(s);`), expected: "10" },
    { name: "for-in: empty array",
      source: main(`var int[] a = new int[0];\n for (v in a) { print(v); }\n print(0);`), expected: "0" },
    { name: "for-in: break",
      source: main(`var int[] a = [5, 6, 7, 8];\n for (v in a) {\n if (v == 7) { break; }\n print(v);\n }`), expected: "5\n6" },
    { name: "for-in: nested",
      source: main(`var int[] a = [1, 2];\n var int[] b = [10, 20];\n for (x in a) {\n for (y in b) { print(x + y); }\n }`),
      expected: "11\n21\n12\n22" },

    { name: "match: literal arms",
      source: `function name(int x) {\n    match (x) {\n        1 => { return 10; }\n        2 => { return 20; }\n        _ => { return 0; }\n    }\n    return -1;\n}\n` +
              main(`print(name(1));\n print(name(2));\n print(name(3));`), expected: "10\n20\n0" },
    { name: "match: no arm matches and no wildcard",
      source: main(`var x = 9;\n match (x) {\n 1 => { print(1); }\n }\n print(0);`), expected: "0" },
    { name: "match: negative pattern",
      source: main(`var x = -1;\n match (x) {\n -1 => { print(1); }\n _ => { print(0); }\n }`), expected: "1" },
    { name: "match: arm with several statements",
      source: main(`var x = 2;\n match (x) {\n 2 => {\n var y = x * 5;\n print(y);\n print(y + 1);\n }\n _ => { print(0); }\n }`),
      expected: "10\n11" },
    { name: "match: inside a loop",
      source: main(`var i = 0;\n while (i < 3) {\n match (i) {\n 0 => { print(100); }\n _ => { print(i); }\n }\n i++;\n }`),
      expected: "100\n1\n2" },

    // ── Functions ────────────────────────────────────────────────────────

    { name: "fn: recursion (fibonacci)",
      source: `function fib(int n) {\n    if (n < 2) { return n; }\n    return fib(n - 1) + fib(n - 2);\n}\n` + main(`print(fib(20));`),
      expected: "6765" },
    { name: "fn: mutual recursion",
      source: `function even(int n) {\n    if (n == 0) { return 1; }\n    return odd(n - 1);\n}\nfunction odd(int n) {\n    if (n == 0) { return 0; }\n    return even(n - 1);\n}\n` +
              main(`print(even(10));\n print(odd(7));`), expected: "1\n1" },
    { name: "fn: deep recursion",
      source: `function depth(int n) {\n    if (n == 0) { return 0; }\n    return 1 + depth(n - 1);\n}\n` + main(`print(depth(10000));`),
      expected: "10000" },
    { name: "fn: six int parameters",
      source: `function f(int a, int b, int c, int d, int e, int g) {\n    return a + b * 2 + c * 3 + d * 4 + e * 5 + g * 6;\n}\n` +
              main(`print(f(1, 2, 3, 4, 5, 6));`), expected: "91" },
    { name: "fn: arguments are evaluated expressions",
      source: `function add(int a, int b) { return a + b; }\n` + main(`var x = 3;\n print(add(x * 2, add(x, 1)));`), expected: "10" },
    { name: "fn: early return from inside a loop",
      source: `function first(int[] a, int want) {\n    var i = 0;\n    while (i < a.len()) {\n        if (a[i] == want) { return i; }\n        i++;\n    }\n    return -1;\n}\n` +
              main(`var int[] a = [4, 8, 15, 16];\n print(first(a, 15));\n print(first(a, 3));`), expected: "2\n-1" },
    { name: "fn: parameters are copies",
      source: `function bump(int x) {\n    x = x + 1;\n    return x;\n}\n` + main(`var a = 1;\n print(bump(a));\n print(a);`),
      expected: "2\n1" },
    { name: "fn: float parameters and return",
      source: `function avg(float a, float b) { return (a + b) / 2.0; }\n` + main(`print(avg(1.0, 2.0));`), expected: "1.5" },
    { name: "fn: float return used in int context",
      source: `function half(float a) { return a / 2.0; }\n` + main(`var int n = half(9.0);\n print(n);`), expected: "4" },
    { name: "fn: int and float parameters mixed",
      source: `function f(int a, float b, int c) {\n    var int bi = b;\n    return a * 100 + bi * 10 + c;\n}\n` +
              main(`print(f(1, 2.0, 3));`), expected: "123"  },
    { name: "fn: float then int parameter",
      source: `function scale(float f, int n) {\n    var float nf = n;\n    return f * nf;\n}\n` + main(`print(scale(1.5, 4));`),
      expected: "6"  },
    { name: "fn: interleaved int and float parameters",
      source: `function f(int a, float b, int c, float d, int e, float g) {\n    var int bi = b * 10.0;\n    var int di = d * 10.0;\n    var int gi = g * 10.0;\n    return a + bi * 10 + c * 100 + di * 1000 + e * 10000 + gi * 100000;\n}\n` +
              main(`print(f(1, 0.2, 3, 0.4, 5, 0.6));`), expected: "654321" },
    { name: "fn: returns string",
      source: `function greet(string n) { return "hi " + n; }\n` + main(`print(greet("bob"));`), expected: "hi bob" },
    { name: "fn: returns array",
      source: `function make(int n) {\n    var int[] a = new int[n];\n    a[n - 1] = 42;\n    return a;\n}\n` +
              main(`var int[] r = make(3);\n print(r.len());\n print(r[2]);`), expected: "3\n42" },
    { name: "fn: returns tuple",
      source: `function minMax(int a, int b) {\n    if (a < b) { return (a, b); }\n    return (b, a);\n}\n` +
              main(`var r = minMax(9, 4);\n print(r.0);\n print(r.1);`), expected: "4\n9", memcheck: true },
    { name: "fn: called as a statement, result ignored",
      source: `function show(int x) {\n    print(x);\n    return 0;\n}\n` + main(`show(5);\n show(6);`), expected: "5\n6" },

    { name: "fn: function named like an x86 instruction",
      source: `function rep(int n) { return n * 2; }\nfunction add(int a, int b) { return a + b; }\nfunction push(int x) { return x + 1; }\n` +
              main(`print(rep(3));\n print(add(1, 2));\n print(push(9));`), expected: "6\n3\n10" },

    // globals
    { name: "globals: int read in main",
      source: `var int G = 41;\n` + main(`print(G + 1);`), expected: "42" },
    { name: "globals: int written by a function",
      source: `var int counter = 0;\nfunction bump() {\n    counter = counter + 1;\n    return 0;\n}\n` + main(`bump();\n bump();\n bump();\n print(counter);`),
      expected: "3"  },
    { name: "globals: string read in main",
      source: `var string NAME = "world";\n` + main(`print("hello " + NAME);`), expected: "hello world" },
    { name: "globals: string printed from a function defined before main",
      source: `var string NAME = "world";\nfunction show() {\n    print(NAME);\n    return 0;\n}\n` + main(`show();`), expected: "world"  },
    { name: "globals: float read in a function",
      source: `var float SCALE = 2.5;\nfunction scaled(float x) { return x * SCALE; }\n` + main(`print(scaled(2.0));`), expected: "5"  },

    { name: "globals: float printed from a function",
      source: `var float G = 2.5;\nfunction show() {\n    print(G);\n    return 0;\n}\n` + main(`show();`), expected: "2.5" },
    { name: "globals: float added to itself in a function",
      source: `var float G = 2.5;\nfunction twice() { return G + G; }\n` + main(`print(twice());`), expected: "5" },
    { name: "globals: float copied to a local in a function",
      source: `var float G = 1.25;\nfunction f() {\n    var y = G;\n    return y * 4.0;\n}\n` + main(`print(f());`), expected: "5" },
    { name: "globals: string concatenated in a function",
      source: `var string P = "pre";\nfunction tag(string s) {\n    var string r = P + s;\n    return r;\n}\n` + main(`print(tag("fix"));`), expected: "prefix" },
    { name: "globals: string compared in a function",
      source: `var string P = "abc";\nfunction same(string s) { return s == P; }\n` + main(`print(same("abc"));\n print(same("abd"));`), expected: "1\n0" },
    { name: "globals: written in a loop, read after a call",
      source: `var int total = 0;\nfunction add(int n) {\n    total = total + n;\n    return 0;\n}\n` + main(`var i = 1;\n while (i <= 4) {\n add(i);\n i++;\n }\n print(total);\n total = 100;\n add(1);\n print(total);`), expected: "10\n101" },

    // ── Arrays ───────────────────────────────────────────────────────────

    { name: "array: literal, index, len",
      source: main(`var int[] a = [3, 1, 4, 1, 5];\n print(a[0]);\n print(a[4]);\n print(a.len());`), expected: "3\n5\n5" },
    { name: "array: new is zero-initialised",
      source: main(`var int[] a = new int[4];\n print(a[0] + a[1] + a[2] + a[3]);`), expected: "0"  },
    { name: "array: size from a variable",
      source: main(`var n = 6;\n var int[] a = new int[n];\n print(a.len());`), expected: "6" },
    { name: "array: write then read with variable index",
      source: main(`var int[] a = new int[5];\n for (var int i = 0; i < 5; i++) { a[i] = i * i; }\n print(a[3]);\n print(a[4]);`),
      expected: "9\n16" },
    { name: "array: index is an expression",
      source: main(`var int[] a = [10, 20, 30];\n var i = 1;\n print(a[i + 1]);\n print(a[a.len() - 3]);`), expected: "30\n10" },
    { name: "array: element used in arithmetic",
      source: main(`var int[] a = [2, 3];\n print(a[0] * a[1] + 1);`), expected: "7" },
    { name: "array: store 64-bit value",
      source: main(`var int[] a = new int[1];\n var int big = 2000000000;\n a[0] = big * 4;\n print(a[0] / 1000);`), expected: "8000000" },
    { name: "array: passed by reference",
      source: `function fill(int[] a, int v) {\n    for (var int i = 0; i < a.len(); i++) { a[i] = v; }\n    return 0;\n}\n` +
              main(`var int[] a = new int[3];\n fill(a, 7);\n print(a[0] + a[1] + a[2]);`), expected: "21" },
    { name: "array: runtime out of bounds (too large)",
      source: main(`var int[] a = new int[3];\n var i = 3;\n print(a[i]);`), expected: "Error: index out of bounds", exitCode: 1 },
    { name: "array: runtime out of bounds (negative)",
      source: main(`var int[] a = new int[3];\n var i = -1;\n print(a[i]);`), expected: "Error: index out of bounds", exitCode: 1  },
    { name: "array: runtime out of bounds on store",
      source: main(`var int[] a = new int[3];\n var i = 5;\n a[i] = 1;\n print(0);`), expected: "Error: index out of bounds", exitCode: 1 },
    { name: "array: runtime out of bounds on store (negative)",
      source: main(`var int[] a = new int[3];\n var i = -2;\n a[i] = 1;\n print(0);`), expected: "Error: index out of bounds", exitCode: 1 },
    { name: "array: constant negative index is a compile error",
      source: main(`var int[] a = [1, 2];\n print(a[-1]);`), shouldError: true },
    { name: "array: large array",
      source: main(`var n = 1000000;\n var int[] a = new int[n];\n for (var int i = 0; i < n; i++) { a[i] = i; }\n var s = 0;\n for (v in a) { s += v; }\n print(s / 1000);`),
      expected: "499999500" },
    { name: "array: slice",
      source: main(`var int[] a = [10, 20, 30, 40, 50];\n var int[] b = a[1..4];\n print(b.len());\n print(b[0]);\n print(b[2]);`),
      expected: "3\n20\n40" },
    { name: "array: slice with variable bounds",
      source: main(`var int[] a = [1, 2, 3, 4, 5];\n var lo = 2;\n var hi = 5;\n var int[] b = a[lo..hi];\n var s = 0;\n for (v in b) { s += v; }\n print(s);`),
      expected: "12"  },
    { name: "array: slice with parameter and expression bounds",
      source: `function mid(int[] a, int lo, int hi) {\n    var int[] b = a[lo + 1..hi - 1];\n    var s = 0;\n    for (v in b) { s = s * 10 + v; }\n    return s;\n}\n` +
              main(`var int[] a = [1, 2, 3, 4, 5, 6];\n print(mid(a, 0, 5));\n print(mid(a, 2, 6));`), expected: "234\n45" },
    { name: "array: empty slice",
      source: main(`var int[] a = [1, 2, 3];\n var int[] b = a[2..2];\n print(b.len());`), expected: "0" },

    { name: "array2d: create, write, read",
      source: main(`var int[][] m = new int[3][4];\n m[2][3] = 9;\n m[0][0] = 1;\n print(m[2][3] + m[0][0] + m[1][1]);`), expected: "10"  },
    { name: "array2d: sizes from variables",
      source: main(`var r = 3;\n var c = 5;\n var int[][] m = new int[r][c];\n for (var int i = 0; i < r; i++) {\n for (var int j = 0; j < c; j++) { m[i][j] = i * 10 + j; }\n }\n print(m[2][4]);`),
      expected: "24" },
    { name: "array2d: row count via len",
      source: main(`var int[][] m = new int[4][2];\n print(m.len());`), expected: "4" },
    { name: "array2d: passed to a function",
      source: `function total(int[][] m, int r, int c) {\n    var s = 0;\n    for (var int i = 0; i < r; i++) {\n        for (var int j = 0; j < c; j++) { s += m[i][j]; }\n    }\n    return s;\n}\n` +
              main(`var int[][] m = new int[2][2];\n m[0][0] = 1;\n m[0][1] = 2;\n m[1][0] = 3;\n m[1][1] = 4;\n print(total(m, 2, 2));`),
      expected: "10" },

    // ── Strings ──────────────────────────────────────────────────────────

    { name: "string: concat chain",
      source: main(`var string a = "ab";\n var string b = a + "cd" + "ef";\n print(b);`), expected: "abcdef" },
    { name: "string: concat with empty string",
      source: main(`var string a = "";\n var string b = a + "x" + "";\n print(b);\n print(len(b));`), expected: "x\n1" },
    { name: "string: len",
      source: main(`print(len("hello"));\n print(len(""));`), expected: "5\n0" },
    { name: "string: char access returns ascii code",
      source: main(`var string s = "AZ";\n print(s[0]);\n print(s[1]);`), expected: "65\n90" },
    { name: "string: equality and inequality",
      source: main(`var string a = "cat";\n var string b = "ca" + "t";\n print(a == b);\n print(a != b);\n print(a == "dog");`),
      expected: "1\n0\n0" },
    { name: "string: inttostr of negative",
      source: main(`print(inttostr(-42));`), expected: "-42" },
    { name: "string: inttostr of 64-bit value",
      source: main(`var int a = 3000000;\n print(inttostr(a * a));`), expected: "9000000000000" },
    { name: "string: strtoint of negative",
      source: main(`print(strtoint("-17") + 1);`), expected: "-16" },
    { name: "string: concat with inttostr",
      source: main(`var n = 7;\n print("n=" + inttostr(n));`), expected: "n=7" },
    { name: "string: result of 300 characters",
      source: main(`var string a = "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789";\n var string b = a + a + a;\n print(len(b));`),
      expected: "300", memcheck: true },
    { name: "string: backslash in a literal is kept as-is (no escape sequences)",
      source: main(`print("a\\nb");\n print(len("a\\nb"));`), expected: "a\\nb\n4" },
    { name: "string: repeated doubling to 1600 characters",
      source: main(`var string a = "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789";\n var string b = a + a;\n var string c = b + b;\n var string d = c + c;\n var string e = d + d;\n print(len(e));\n print(e == d + d);`),
      expected: "1600\n1", memcheck: true },
    { name: "string: literal containing an apostrophe",
      source: main(`print("it's");`), expected: "it's"  },
    { name: "string: reassigned from itself in a while loop",
      source: `function pad(int n, int width) {\n    var string s = inttostr(n);\n    while (len(s) < width) {\n        s = "0" + s;\n    }\n    return s;\n}\n` +
              main(`print(pad(42, 5));`), expected: "00042", memcheck: true },
    { name: "string: built up in a while loop",
      source: main(`var string s = "";\n var i = 0;\n while (i < 5) {\n s = s + "ab";\n i++;\n }\n print(s);`),
      expected: "ababababab", memcheck: true },
    { name: "string: built up in a for loop",
      source: main(`var string s = "";\n for (var int i = 0; i < 5; i++) {\n s = s + inttostr(i);\n }\n print(s);`),
      expected: "01234", memcheck: true },

    // ── Chars ────────────────────────────────────────────────────────────

    { name: "char: literal is its ascii code",
      source: main(`var int c = 'A';\n print(c);\n print('z' - 'a');`), expected: "65\n25" },
    { name: "char: printchar with a variable",
      source: main(`var int c = 'H';\n printchar(c);\n printchar(c + 1);`), expected: "HI", exact: true },
    { name: "char: printchar with a char literal",
      source: main(`printchar('o');\n printchar('k');`), expected: "ok", exact: true },
    { name: "char: printchar with an int literal",
      source: main(`printchar(72);\n printchar(10);`), expected: "H\n", exact: true },
    { name: "char: comparison",
      source: main(`var int c = 'm';\n if (c >= 'a' && c <= 'z') { print(1); } else { print(0); }`), expected: "1" },

    // ── Tuples ───────────────────────────────────────────────────────────

    { name: "tuple: three elements",
      source: main(`var t = (10, 20, 30);\n print(t.0 + t.1 + t.2);`), expected: "60" },
    { name: "tuple: elements are expressions",
      source: main(`var a = 3;\n var t = (a * 2, a + 1);\n print(t.0);\n print(t.1);`), expected: "6\n4" },

    // ── Structs ──────────────────────────────────────────────────────────

    { name: "struct: fields, method, mutation",
      source: `struct Point {\n    var x: int;\n    var y: int;\n    fn distSq() { return this.x * this.x + this.y * this.y; }\n}\n` +
              main(`var p = Point { x: 3, y: 4 };\n print(p.distSq());\n p.x = 6;\n p.y = 8;\n print(p.distSq());`),
      expected: "25\n100" },
    { name: "struct: method with parameters",
      source: `struct Acc {\n    var base: int;\n    fn plus(int a, int b) { return this.base + a + b; }\n}\n` +
              main(`var a = Acc { base: 100 };\n print(a.plus(20, 3));`), expected: "123" },
    { name: "struct: method calls another method via this",
      source: `struct R {\n    var w: int;\n    var h: int;\n    fn area() { return this.w * this.h; }\n    fn double() { return this.area() * 2; }\n}\n` +
              main(`var r = R { w: 3, h: 5 };\n print(r.double());`), expected: "30" },
    { name: "struct: passed to a function and modified",
      source: `struct Box {\n    var v: int;\n}\nfunction setv(Box b, int v) {\n    b.v = v;\n    return 0;\n}\n` +
              main(`var b = Box { v: 1 };\n setv(b, 9);\n print(b.v);`), expected: "9" },
    { name: "struct: string field",
      source: `struct P {\n    var name: string;\n}\n` + main(`var p = P { name: "ann" };\n print(p.name);\n print(len(p.name));`), expected: "ann\n3" },
    { name: "struct: const field assignment is an error",
      source: `struct C {\n    const id: int;\n}\n` + main(`var c = C { id: 1 };\n c.id = 2;`), shouldError: true },
    { name: "struct: three-level inheritance",
      source: `struct A {\n    var a: int;\n    fn who() { return 1; }\n}\nstruct B extends A {\n    var b: int;\n    overrides {\n        fn who() { return 2; }\n    }\n}\nstruct C extends B {\n    var c: int;\n    overrides {\n        fn who() { return 3; }\n    }\n}\n` +
              main(`var x = C { a: 1, b: 2, c: 3 };\n print(x.a + x.b + x.c);\n print(x.who());`), expected: "6\n3" },
    { name: "struct: dynamic dispatch through a parent-typed parameter",
      source: `struct Animal {\n    var legs: int;\n    fn speak() { return 0; }\n}\nstruct Dog extends Animal {\n    var good: int;\n    overrides {\n        fn speak() { return 1; }\n    }\n}\nfunction talk(Animal a) { return a.speak(); }\n` +
              main(`var d = Dog { legs: 4, good: 1 };\n var a = Animal { legs: 2 };\n print(talk(d));\n print(talk(a));`),
      expected: "1\n0" },
    { name: "struct: inherited method uses child's fields",
      source: `struct Base {\n    var n: int;\n    fn get() { return this.n; }\n}\nstruct Kid extends Base {\n    var m: int;\n}\n` +
              main(`var k = Kid { n: 5, m: 6 };\n print(k.get());\n print(k.m);`), expected: "5\n6" },
    { name: "struct: method assigns a field through this",
      source: `struct Counter {\n    var n: int;\n    fn inc() {\n        this.n = this.n + 1;\n        return 0;\n    }\n}\n` +
              main(`var c = Counter { n: 0 };\n c.inc();\n c.inc();\n print(c.n);`), expected: "2"  },
    { name: "struct: setter method with a parameter",
      source: `struct Box {\n    var v: int;\n    fn set(int x) {\n        this.v = x * 2;\n        return 0;\n    }\n}\n` +
              main(`var b = Box { v: 0 };\n b.set(21);\n print(b.v);`), expected: "42" },
    { name: "struct: inherited mutating method on a child instance",
      source: `struct Base {\n    var n: int;\n    fn bump() {\n        this.n = this.n + 10;\n        return 0;\n    }\n}\nstruct Kid extends Base {\n    var m: int;\n}\n` +
              main(`var k = Kid { n: 1, m: 2 };\n k.bump();\n print(k.n);\n print(k.m);`), expected: "11\n2" },
    { name: "struct: returned from a function",
      source: `struct V {\n    var x: int;\n}\nfunction mk(int x) { return V { x: x }; }\n` + main(`var V v = mk(7);\n print(v.x);`), expected: "7"  },
    { name: "struct: method call on a returned struct",
      source: `struct P {\n    var x: int;\n    var y: int;\n    fn sum() { return this.x + this.y; }\n}\nfunction mk(int a) { return P { x: a, y: a * 2 }; }\n` +
              main(`var P p = mk(5);\n print(p.sum());\n p.y = 1;\n print(p.sum());`), expected: "15\n6" },
    { name: "struct: annotation naming an unknown struct is an error",
      source: `function mk() { return 1; }\n` + main(`var Nope n = mk();\n print(n.x);`), shouldError: true },
    { name: "struct: unknown field is an error",
      source: `struct S {\n    var a: int;\n}\n` + main(`var s = S { a: 1 };\n print(s.b);`), shouldError: true },
    { name: "struct: unknown method is an error",
      source: `struct S {\n    var a: int;\n    fn f() { return 1; }\n}\n` + main(`var s = S { a: 1 };\n print(s.g());`), shouldError: true },

    // ── Imports ──────────────────────────────────────────────────────────

    { name: "import: local header",
      source: `import util;\n` + main(`print(triple(5));`),
      files: { "headers/util.l": `function triple(int x) { return x * 3; }\n` }, expected: "15" },
    { name: "import: header importing another header",
      source: `import a;\n` + main(`print(fa());`),
      files: { "headers/a.l": `import b;\nfunction fa() { return fb() + 1; }\n`, "headers/b.l": `function fb() { return 41; }\n` }, expected: "42" , bug: "B19" },
    { name: "import: same module twice is deduplicated",
      source: `import util;\nimport util;\n` + main(`print(triple(2));`),
      files: { "headers/util.l": `function triple(int x) { return x * 3; }\n` }, expected: "6" },
    { name: "import: local header shadows stdlib module of the same name",
      source: `import math;\n` + main(`print(mine());`),
      files: { "headers/math.l": `function mine() { return 5; }\n` }, expected: "5" },
    { name: "import: missing module is an error",
      source: `import doesnotexist;\n` + main(`print(1);`), shouldError: true, errorMatch: /Cannot find module/ },

    // ── Inline assembly ──────────────────────────────────────────────────

    { name: "asm: multi-line block",
      source: main(`asm {\n nop\n nop\n }\n print(1);`), expected: "1" },

    // ── Built-ins ────────────────────────────────────────────────────────

    { name: "builtin: print float",
      source: main(`print(2.5);\n print(-0.125);`), expected: "2.5\n-0.125" },
    { name: "builtin: input",
      source: main(`var a = input();\n var b = input();\n print(a * b);`), stdin: "6\n7\n", expected: "42" },
    { name: "builtin: input negative number used in arithmetic",
      source: main(`var a = input();\n var int big = a * 1000000;\n if (big < 0) { print(1); } else { print(0); }`),
      stdin: "-5\n", expected: "1" },
    { name: "builtin: input above 2^31",
      source: main(`var a = input();\n print(a / 1000);`), stdin: "5000000000\n", expected: "5000000" },
    { name: "builtin: inputstr",
      source: main(`var string s = inputstr();\n print(len(s));\n print(s + "!");`), stdin: "hello\n", expected: "5\nhello!" },
    { name: "builtin: strtoint/inttostr round trip",
      source: main(`var string s = inttostr(12345);\n print(strtoint(s) + 1);`), expected: "12346" },

    // ── Floats ───────────────────────────────────────────────────────────

    { name: "float: arithmetic",
      source: main(`var a = 1.5;\n var b = 0.25;\n print(a + b);\n print(a - b);\n print(a * b);\n print(a / b);`),
      expected: "1.75\n1.25\n0.375\n6" },
    { name: "float: all comparisons",
      source: main(`var a = 1.5;\n var b = 2.5;\n print(a < b);\n print(a <= b);\n print(a > b);\n print(a >= b);\n print(a == b);\n print(a != b);`),
      expected: "1\n1\n0\n0\n0\n1" },
    { name: "float: negation of a variable",
      source: main(`var a = 2.5;\n var b = -a;\n print(b);`), expected: "-2.5" },
    { name: "float: compound assignment",
      source: main(`var x = 1.0;\n x += 0.5;\n x *= 4.0;\n x -= 1.0;\n x /= 2.0;\n print(x);`), expected: "2.5" },
    { name: "float: accumulate in a loop",
      source: main(`var s = 0.0;\n var i = 0;\n while (i < 4) {\n s = s + 0.5;\n i++;\n }\n print(s);`), expected: "2" },
    { name: "float: int + float is a type error",
      source: main(`var f = 1.5;\n var n = 2;\n print(f + n);`), shouldError: true , bug: "B20" },

    // ── Memory management ────────────────────────────────────────────────

    { name: "memory: strings allocated in a while loop",
      source: main(`var i = 0;\n while (i < 2000) {\n var string s = inttostr(i) + "x";\n i++;\n }\n print(1);`), expected: "1", memcheck: true },
    { name: "memory: arrays allocated in a while loop",
      source: main(`var i = 0;\n while (i < 2000) {\n var int[] a = new int[100];\n a[99] = i;\n i++;\n }\n print(1);`), expected: "1", memcheck: true },
    { name: "memory: 2D array freed",
      source: main(`var int[][] m = new int[10][10];\n m[9][9] = 1;\n print(m[9][9]);`), expected: "1", memcheck: true },
    { name: "memory: returned string is not freed by the callee",
      source: `function mk(int n) {\n    var string s = inttostr(n) + "!";\n    return s;\n}\n` + main(`var string a = mk(1);\n var string b = mk(2);\n print(a + b);`),
      expected: "1!2!", memcheck: true },
    { name: "memory: function returning a string literal",
      source: `function name() { return "lit"; }\n` + main(`var string s = name();\n print(s);`), expected: "lit", memcheck: true },
    { name: "memory: function returning its string parameter",
      source: `function same(string s) { return s; }\n` + main(`var string a = inttostr(5);\n var string b = same(a);\n print(b);`),
      expected: "5", memcheck: true , bug: "B21" },
    { name: "memory: heap string assigned only in an untaken branch",
      source: `function maybe(int c) {\n    if (c) {\n        var string s = inttostr(c);\n        print(s);\n    }\n    return 0;\n}\n` + main(`maybe(0);\n maybe(3);`),
      expected: "3", memcheck: true },
    { name: "memory: string allocated conditionally inside a loop",
      source: main(`var i = 0;\n while (i < 4) {\n if (i % 2 == 0) {\n var string s = inttostr(i);\n print(s);\n }\n i++;\n }`),
      expected: "0\n2", memcheck: true },
    { name: "memory: array allocated conditionally inside a loop",
      source: main(`var i = 0;\n var t = 0;\n while (i < 5) {\n if (i != 2) {\n var int[] a = new int[3];\n a[1] = i;\n t += a[1];\n }\n i++;\n }\n print(t);`),
      expected: "8", memcheck: true },
    { name: "memory: 2D array allocated conditionally inside a loop",
      source: main(`var i = 0;\n while (i < 3) {\n if (i == 1) {\n var int[][] m = new int[2][2];\n m[1][1] = 7;\n print(m[1][1]);\n }\n i++;\n }`),
      expected: "7", memcheck: true },
    { name: "memory: different heap value returned on each path",
      source: `function pick(int c) {\n    if (c) {\n        var string a = inttostr(1);\n        return a;\n    }\n    var string b = inttostr(2);\n    return b;\n}\n` + main(`print(pick(0));\n print(pick(1));`),
      expected: "2\n1", memcheck: true },
    { name: "memory: ownership transfer by assignment",
      source: main(`var string a = inttostr(7);\n var string b = a;\n print(b);`), expected: "7", memcheck: true },
    { name: "memory: heap array reassigned in a while loop",
      source: main(`var int[] a = new int[1];\n var i = 0;\n while (i < 3) {\n a = new int[i + 1];\n a[i] = i;\n i++;\n }\n var int[] other = new int[3];\n var k = 2;\n other[k] = 99;\n print(a[k]);`),
      expected: "2", memcheck: true },
    { name: "memory: continue in a loop that allocates",
      source: main(`var i = 0;\n var n = 0;\n while (i < 10) {\n var string s = inttostr(i);\n i++;\n if (i % 2 == 0) { continue; }\n n += len(s);\n }\n print(n);`),
      expected: "5", memcheck: true },
    { name: "memory: break in a loop that allocates",
      source: main(`var i = 0;\n while (true) {\n var string s = inttostr(i) + "!";\n if (i == 3) {\n print(s);\n break;\n }\n i++;\n }`),
      expected: "3!", memcheck: true },
    { name: "memory: declared in an outer loop, reassigned in an inner loop",
      source: main(`var i = 0;\n while (i < 3) {\n var string s = "";\n var j = 0;\n while (j < 3) {\n s = s + inttostr(j);\n j++;\n }\n print(s);\n i++;\n }`),
      expected: "012\n012\n012", memcheck: true },
    { name: "memory: string parameter reassigned in a loop",
      source: `function repeat(string s, int n) {\n    var i = 1;\n    while (i < n) {\n        s = s + "x";\n        i++;\n    }\n    return len(s);\n}\n` + main(`print(repeat("ab", 4));`),
      expected: "5", memcheck: true },
    { name: "memory: global string reassigned in a loop",
      source: `var string G = "";\nfunction build() {\n    var i = 0;\n    while (i < 3) {\n        G = G + "g";\n        i++;\n    }\n    return 0;\n}\n` + main(`build();\n print(G);`),
      expected: "ggg", memcheck: true },
    { name: "memory: return from inside a loop that allocates",
      source: `function find() {\n    var i = 0;\n    while (i < 10) {\n        var string s = inttostr(i);\n        if (i == 4) { return i; }\n        i++;\n    }\n    return -1;\n}\n` + main(`print(find());`),
      expected: "4", memcheck: true },
    { name: "memory: struct instances in a loop",
      source: `struct P {\n    var x: int;\n}\n` + main(`var i = 0;\n var s = 0;\n while (i < 100) {\n var p = P { x: i };\n s += p.x;\n i++;\n }\n print(s);`),
      expected: "4950", memcheck: true },

    { name: "memory: string literal returned from a function called in a while loop",
      source: `function name() { return "lit"; }\n` + main(`var i = 0;\n while (i < 3) {\n var string s = name();\n print(s);\n i++;\n }`),
      expected: "lit\nlit\nlit", memcheck: true, bug: "B28" },
    { name: "memory: string parameter returned from a function called in a while loop",
      source: `function same(string s) {\n    var string r = s;\n    return r;\n}\n` + main(`var string a = inttostr(5);\n var i = 0;\n while (i < 3) {\n var string b = same(a);\n print(b);\n i++;\n }`),
      expected: "5\n5\n5", memcheck: true, bug: "B28" },

    // ── Copy propagation ─────────────────────────────────────────────────

    { name: "copyprop: copy of a parameter keeps its value after the parameter changes",
      source: `function g(int a) {\n    var b = a;\n    a = 5;\n    print(b + 0);\n    return 0;\n}\n` + main(`g(1);`), expected: "1" },
    { name: "copyprop: copy of a variable keeps its value after the variable changes",
      source: main(`var int a = input();\n if (a > 0) { print(0); }\n var b = a;\n a = 5;\n print(b + 0);`), stdin: "1\n", expected: "0\n1" },
    { name: "copyprop: postfix increment as a call argument",
      source: `function show(int x) {\n    print(x);\n    return 0;\n}\n` + main(`var a = 1;\n show(a++);\n print(a);`), expected: "1\n2" },
    { name: "copyprop: postfix increment as an array index",
      source: main(`var int[] a = [10, 20, 30];\n var i = 0;\n print(a[i++]);\n print(i);`), expected: "10\n1" },

    // ── Calls: argument conversion ───────────────────────────────────────

    { name: "call: int argument to a float parameter is converted",
      source: `import math;\n` + main(`print(math_sqrt(4));`), expected: "2" },
    { name: "call: int variable to a float parameter is converted",
      source: `function half(float x) { return x / 2.0; }\n` + main(`var n = 5;\n print(half(n));`), expected: "2.5" },

    { name: "call: float argument to an int parameter is truncated",
      source: `function twice(int n) { return n * 2; }\n` + main(`print(twice(3.9));\n print(twice(-3.9));`), expected: "6\n-6" },
    { name: "call: stdlib float parameter given an int",
      source: `import math;\n` + main(`print(math_toint(7));\n print(math_floor(-3));`), expected: "7\n-3" },
    { name: "call: several converted arguments in one call",
      source: `function f(float a, int b, float c) {\n    var int ai = a * 10.0;\n    var int ci = c * 10.0;\n    return ai + b * 100 + ci * 1000;\n}\n` + main(`print(f(1, 2.7, 3));`),
      expected: "30210" },

    // ── More built-ins ───────────────────────────────────────────────────

    { name: "builtin: inputstr reads a whole line",
      source: main(`var string s = inputstr();\n print(s);`), stdin: "hello world\n", expected: "hello world", bug: "B25" },

    // ── Memory: leaks ────────────────────────────────────────────────────

    { name: "memory: function-level heap string is freed (no leak)",
      source: main(`var string s = inttostr(5);\n print(s);`), expected: "5", memcheck: true, leaks: true, bug: "B24" },
    { name: "memory: function-level heap array is freed (no leak)",
      source: main(`var int[] a = new int[4];\n a[0] = 1;\n print(a[0]);`), expected: "1", memcheck: true, leaks: true, bug: "B24" },

    // ── Type checking ────────────────────────────────────────────────────

    { name: "types: variable initialised from a call can be reassigned",
      source: `function one() { return 1; }\n` + main(`var x = one();\n x = 2;\n print(x);`), expected: "2" },
    { name: "types: variable initialised from input() can be reassigned",
      source: main(`var a = input();\n a = 5;\n print(a);`), stdin: "4\n", expected: "5" },
    { name: "types: constant index checked against a reassigned array's size",
      source: main(`var int[] a = new int[1];\n a = new int[3];\n a[2] = 7;\n print(a[2]);`), expected: "7" },
    { name: "types: constant index equal to the size is a compile error",
      source: main(`var int[] a = [1, 2, 3];\n print(a[3]);`), shouldError: true },

    // ── Compile errors ───────────────────────────────────────────────────

    { name: "error: undefined variable", source: main(`print(nope);`), shouldError: true, errorMatch: /Undefined/ },
    { name: "error: undefined function", source: main(`nope(1);`), shouldError: true, errorMatch: /Undefined function/ },
    { name: "error: wrong argument count",
      source: `function f(int a) { return a; }\n` + main(`print(f(1, 2));`), shouldError: true, errorMatch: /expects 1 args/ },
    { name: "error: string declared as int", source: main(`var int x = "s";`), shouldError: true, errorMatch: /mismatch/ },
    { name: "error: assigning string to int variable", source: main(`var x = 1;\n x = "s";`), shouldError: true, errorMatch: /mismatch/ },
    { name: "error: string + int", source: main(`var s = "a" + 1;`), shouldError: true },
    { name: "error: duplicate declaration in the same scope", source: main(`var a = 1;\n var a = 2;`), shouldError: true, errorMatch: /Duplicate/ },
    { name: "error: break outside a loop", source: main(`break;`), shouldError: true },
    { name: "error: error message has line:col",
      source: `main() {\n    var a = 1;\n    print(zzz);\n    return 0;\n}`, shouldError: true, errorMatch: /3:\d+: Undefined/ },
    { name: "error: missing semicolon on the last statement",
      source: `main() {\n    print(1)\n}`, shouldError: true },
    { name: "error: unclosed block",
      source: `main() {\n    print(1);\n`, shouldError: true },
];

runSuite("Language tests", tests);
